# Primer on linear algebra in Numpy

## Instructions:
* Go through the notebook and complete the tasks. 
* Make sure you understand the examples given. If you need help, refer to the Essential readings or the documentation link provided, or go to the discussion forum. 
* When a question allows a free-form answer (e.g. what do you observe?), create a new markdown cell below and answer the question in the notebook. 
* Save your notebooks when you are done.
 
**Task 1:**
Go through the tutorial on Linear Algebra in Python here: http://ml-cheatsheet.readthedocs.io/en/latest/linear_algebra.html.
Paste and run the code from the tutorial in the empty cell below (or create new empty cells below) to get more familiar with the material.


In [2]:
import numpy as np

#Code here - use code samples from link above
import numpy as np

# Creating a 2D array (matrix)
A = np.array([[1, 2], [3, 4]])
print("Matrix A:")
print(A)

# Transpose of a matrix
A_T = A.T
print("\nTranspose of A:")
print(A_T)

# Determinant of a matrix
det_A = np.linalg.det(A)
print("\nDeterminant of A:")
print(det_A)

# Inverse of a matrix
inv_A = np.linalg.inv(A)
print("\nInverse of A:")
print(inv_A)

# Matrix multiplication
B = np.array([[5, 6], [7, 8]])
C = np.dot(A, B)
print("\nMatrix multiplication A * B:")
print(C)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of A:")
print(eigenvalues)
print("Eigenvectors of A:")
print(eigenvectors)


Matrix A:
[[1 2]
 [3 4]]

Transpose of A:
[[1 3]
 [2 4]]

Determinant of A:
-2.0000000000000004

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Matrix multiplication A * B:
[[19 22]
 [43 50]]

Eigenvalues of A:
[-0.37228132  5.37228132]
Eigenvectors of A:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


**Task 2:**
Create the following matrices:

$X=\begin{bmatrix} 2 & 3 & 4 \\ 1 & 2 &3 \end{bmatrix},Y=\begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 &0\\ 0 & 0 & 1 \end{bmatrix}$ 

Then do the following:
1.	Multiply ```X``` with ```Y``` (```Z1=X*Y=XY```) and print the result. What do you observe? 
2.	Multiply ```X``` with ```Y``` transpose (```Z2=X*Y.T```) and print the result. What do you observe? 
3.	What can you tell about matrix ```Y```, given ```Z1``` and ```Z2```? 

In [3]:
# Create matrices X and Y
X = np.array([[2, 1, 3], [2, 4, 3]])
Y = np.array([[0, 1, 0], [1, 0, 0], [1, 0, 1]])

# Multiply X with Y (Z1 = X * Y)
Z1 = np.dot(X, Y)
print("Z1 (X * Y):")
print(Z1)

# Multiply X with Y transpose (Z2 = X * Y.T)
Z2 = np.dot(X, Y.T)
print("\nZ2 (X * Y.T):")
print(Z2)

# Observations
# Z1 shows how the elements of X interact with Y. The dimensions must align for the multiplication.
# Z2 results in a different shape and may provide insight into how the original rows of X relate to the rows of Y.


Z1 (X * Y):
[[4 2 3]
 [7 2 3]]

Z2 (X * Y.T):
[[1 2 5]
 [4 2 5]]


**Task 3:** 
Create a 2x2 identity matrix ```I``` using the NumPy function ```eye(dim)``` $$ I=\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} $$


In [4]:
#Code here
# Create a 2x2 identity matrix
I = np.eye(2)
print("\nIdentity Matrix I:")
print(I)



Identity Matrix I:
[[1. 0.]
 [0. 1.]]


**Task 4:** 
1. Multiply (using dot) matrix ```I``` with the vector ```x``` defined below: $$Ix$$
2. Print the output.
3. What do you observe? 



In [5]:

# Define vector x
x = np.array([2, 3])
print("\nVector x:")
print(x)

# Multiply I with x
result_Ix = np.dot(I, x)
print("\nResult of I * x:")
print(result_Ix)

# Observation
# The output should be the same as the vector x since multiplying by an identity matrix returns the original vector.



Vector x:
[2 3]

Result of I * x:
[2. 3.]


**Task 5:**
1.	Multiply (using dot) matrix ```I``` with the vector ```x``` defined below: $$Ix$$
2.	Print the output.
3.	What do you observe? 


In [6]:
# Define 2D matrix X
X = np.array([[2, 3], [4, 5]])
print("\nMatrix X:")
print(X)

# Multiply I with the first row of X
result_Ix = np.dot(I, X[0])  # Multiply with the first row
print("\nResult of I * first row of X:")
print(result_Ix)

# Observation
# The output should again match the first row of X since I is the identity matrix.



Matrix X:
[[2 3]
 [4 5]]

Result of I * first row of X:
[2. 3.]


**Task 6:**
1. Multiply (using dot) matrix $X$ with the inverse matrix, $X^{-1}$ (use the NumPy function ```linalg.inv``` to do so): $XX^{-1}$
2. What do you observe? 




In [7]:
# Create a 2x2 matrix X
X = np.array([[1, 2], [0, 1]])

# Multiply X with its inverse
X_inv = np.linalg.inv(X)
result = np.dot(X, X_inv)
print("\nResult of X * X^-1:")
print(result)

# Observation
# The result should be the identity matrix, confirming that multiplying a matrix by its inverse yields the identity matrix.



Result of X * X^-1:
[[1. 0.]
 [0. 1.]]
